-- DROP TABLE IF EXISTS `zt_info`;
-- DROP TABLE IF EXISTS `zt_infolib`;
-- DROP TABLE IF EXISTS `zt_infomodule`;
-- DELETE FROM `zt_action` WHERE `objectType` LIKE  '%info%';
-- DELETE FROM `zt_grouppriv` WHERE `module` LIKE `%info%`;
-- DELETE FROM `zt_config` WHERE `key` = 'infoplugin';
-- DELETE FROM `zt_userquery` WHERE `module` = 'info';
