-- DROP TABLE IF EXISTS `zt_infoasset`;
CREATE TABLE IF NOT EXISTS `zt_infoasset` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `lib` varchar(30) NOT NULL,
  `module` mediumint(8) unsigned NOT NULL default '0',
  `createdBy` varchar(30) NOT NULL default '',
  `createdDate` datetime NOT NULL,
  `lastEditedBy` varchar(30) NOT NULL default '',
  `lastEditedDate` datetime NOT NULL,
  `editedCount` smallint(6) NOT NULL default '0',
  `deleted` enum('0','1') NOT NULL default '0',
  `company` mediumint(8) unsigned NOT NULL,
  `hostname` char(30) NOT NULL,
  `address` char(30) NOT NULL default '',
  `extendaddress` char(30) NOT NULL default '',
  `os` char(30) NOT NULL default '',
  `username` char(255) NOT NULL default '',
  `password` char(255) NOT NULL default '',
  `status` varchar(30) NOT NULL default '0',
  `duty` char(30) NOT NULL default '',
  `position` varchar(30) NOT NULL default '',
  `devicenumber` varchar(60) NOT NULL default '',
  `rootusername` char(255) NOT NULL default '',
  `rootpassword` char(255) NOT NULL default '',
  `codeversion` char(30) NOT NULL default '',
  `name` varchar(30) NOT NULL,
  `serial` varchar(255) NOT NULL default '',
  `model` varchar(255) NOT NULL default '',
  `cpu` varchar(30) NOT NULL default '',
  `memory` varchar(30) NOT NULL default '',
  `disk` varchar(30) NOT NULL default '',
  `graphics` varchar(30) NOT NULL default '',
  `price` mediumint(8) unsigned NOT NULL default '0',
  `netvalue` mediumint(8) unsigned NOT NULL default '0',
  `code` varchar(60) NOT NULL default '',
  `from` varchar(255) NOT NULL default '',
  `registdate` date NOT NULL default '0000-00-00',
  `lend` varchar(255) NOT NULL default '',
  `lenddate` date NOT NULL default '0000-00-00',
  `returndate` date NOT NULL default '0000-00-00',
  `assetcomment` varchar(255) NOT NULL default '',
  PRIMARY KEY  (`id`),
  KEY `company` (`company`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
-- 为infolib库增加type字段用来判断是公告库还是资产库
ALTER TABLE `zt_infolib` ADD `type` char(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL AFTER `name`;
UPDATE `zt_infolib` SET `type` = 'info'